openapi: 3.0.3
info:
  title: Examen - OpenAPI 3.0
  description: Este es una Api basado en la especificación OpenAPI 3.0. Se Puede obtener más información sobre la API en https://pruebatecnicav2.mx.
  termsOfService: http://pruebatecnicav2.mx/terms/
  contact:
    email: pruebatecnicav2@mail.mx
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.01
externalDocs:
  description: Más información sobre el examen
  url: http://pruebatecnicav2.mx
servers:
  - url: http://localhost:8080
tags:
  - name: persona
    description: Operaciones acerca persona
paths:
  /persona/{personaId}:
    get:
      tags:
        - persona
      summary: Encuentra una persona por ID
      description: El Id de persona retorna
      operationId: obtienePersonaPorId
      parameters:
        - name: personaId
          in: path
          description: El Id de persona retorna
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Persona'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Persona'
        '400':
          description: Id Invalido
        '404':
          description: Persona no encontrada
  /persona:
    get:
      tags:
        - persona
      summary: Encuentra todas las personas
      description: Se obtiene todas las personas mediante una lista
      operationId: obtieneTodasLasPersonas
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Persona'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Persona'
        '404':
          description: Personas no encontradas
components:
  schemas:
    Persona:
      required:
        - nombre
        - apellidos
        - rfc
        - curp
        - edad
        - sexo
        - nacionalidad
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nombre:
          type: string
        apellidos:
          type: string
        rfc:
          type: string
        curp:
          type: string
        edad:
          type: string
        sexo:
          type: string
        nacionalidad:
          type: string
      xml:
        name: persona